Repository AY2425S2-CS2113-F14-4/tp, pull requests merged in 2025-04, with the labels that each got.

#75 Branch Junit test ByeCommand
  src/main/java/seedu/command/ByeCommand.java
  src/main/java/seedu/ezmealplan/EZMealPlan.java
  src/main/java/seedu/storage/Storage.java
  src/test/java/seedu/command/ByeCommandTest.java
  src/test/java/seedu/command/ListCommandTest.java
  src/test/java/seedu/command/MealCommandTest.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: type.Task, priority.High

#67 Branch dg second
  docs/DeveloperGuide.md
  docs/diagrams/BootingUpEZMealPlan.png
  docs/diagrams/ConstructingMainMeals.png
  docs/diagrams/Food.puml
  docs/diagrams/ListCommand.png
  docs/diagrams/MealCommand.png
  docs/diagrams/RunCommandSequenceDiagram.png
  docs/img.png
  puml/RunCommandSequenceDiagram.puml
  src/main/java/seedu/ezmealplan/EZMealPlan.java
Labels: type.Task, priority.High

#76 Branch userguide
  docs/UserGuide.md
  src/main/java/seedu/ui/UserInterface.java
  src/test/java/seedu/ui/UserInterfaceTest.java
Labels: type.Task, priority.High

#79 Create teng-yong-quan.md for ppp
  docs/UserGuide.md
  docs/team/teng-yong-quan.md
Labels: type.Task, priority.High

#86 Junit test for EZMealPlan
  src/test/java/seedu/command/ListCommandTest.java
  src/test/java/seedu/command/MealCommandTest.java
  src/test/java/seedu/ezmealplan/EZMealPlanTest.java
Labels: priority.Medium

#90 Update documentation
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/wangyanjie.md
  src/main/java/seedu/command/ListCommand.java
  src/main/java/seedu/command/MealCommand.java
  src/test/java/seedu/ezmealplan/EZMealPlanTest.java
Labels: priority.High

#87 Perform code refactoring and other adjustments
  data/inventoryList.txt
  data/recipesList.txt
  data/wishList.txt
  src/main/java/seedu/checkers/RemoveDeleteChecker.java
  src/main/java/seedu/checkers/ViewChecker.java
  src/main/java/seedu/command/BuyCommand.java
  src/main/java/seedu/command/ByeCommand.java
  src/main/java/seedu/command/ClearCommand.java
  src/main/java/seedu/command/ConsumeCommand.java
  src/main/java/seedu/command/CreateCommand.java
  src/main/java/seedu/command/DeleteCommand.java
  src/main/java/seedu/command/FilterSelectCommand.java
  src/main/java/seedu/command/HelpCommand.java
  src/main/java/seedu/command/RecipesCommand.java
  src/main/java/seedu/command/RecommendCommand.java
  src/main/java/seedu/command/RemoveDeleteCommand.java
  src/main/java/seedu/command/SelectCommand.java
  src/main/java/seedu/command/ViewCommand.java
  src/main/java/seedu/command/WishlistCommand.java
  src/main/java/seedu/exceptions/InvalidKeywordIndexException.java
  src/main/java/seedu/exceptions/InvalidViewKeywordException.java
  src/main/java/seedu/exceptions/ViewEmptyListException.java
  src/main/java/seedu/exceptions/ViewIndexOutOfRangeException.java
  src/main/java/seedu/ezmealplan/EZMealPlan.java
  src/main/java/seedu/food/Ingredient.java
  src/main/java/seedu/food/Inventory.java
  src/main/java/seedu/food/Meal.java
  src/main/java/seedu/logic/MealManager.java
  src/main/java/seedu/meallist/MainMeals.java
  src/main/java/seedu/meallist/MealList.java
  src/main/java/seedu/meallist/RecipesList.java
  src/main/java/seedu/meallist/UserMeals.java
  src/main/java/seedu/meallist/WishList.java
  src/main/java/seedu/parser/Parser.java
  src/main/java/seedu/storage/Storage.java
  src/main/java/seedu/ui/UserInterface.java
  src/test/java/seedu/command/ByeCommandTest.java
  src/test/java/seedu/command/ClearCommandTest.java
  src/test/java/seedu/command/CreateCommandTest.java
  src/test/java/seedu/command/FilterCommandTest.java
  src/test/java/seedu/command/RecipesCommandTest.java
  src/test/java/seedu/command/SelectCommandTest.java
  src/test/java/seedu/command/ViewCommandTest.java
  src/test/java/seedu/command/WishlistCommandTest.java
  src/test/java/seedu/ezmealplan/EZMealPlanTest.java
  src/test/java/seedu/meallist/MealListTest.java
  src/test/java/seedu/ui/UserInterfaceTest.java
  text-ui-test/EXPECTED.TXT
Labels: type.Task, priority.High

#95 Add InventoryCommand
  src/main/java/seedu/command/InventoryCommand.java
  src/main/java/seedu/parser/Parser.java
  src/main/java/seedu/ui/UserInterface.java
Labels: type.Task, priority.High

#97 Update DG for SelectCommand
  docs/DeveloperGuide.md
  docs/diagrams/RecipesCommand.png
  docs/diagrams/SelectCommand.png
  docs/diagrams/WishlistCommand.png
  docs/team/wangyanjie.md
Labels: priority.High

#105 Rename PPP
  docs/AboutUs.md
  docs/team/olsonwangyj.md
Labels: priority.High

#177 Branch fix mistakes
  docs/UserGuide.md
  src/main/java/seedu/command/BuyCommand.java
  src/main/java/seedu/command/ConsumeCommand.java
  src/main/java/seedu/command/CreateCommand.java
  src/main/java/seedu/command/FilterCommand.java
  src/main/java/seedu/command/FilterSelectCommand.java
  src/main/java/seedu/command/RecommendCommand.java
  src/main/java/seedu/command/RemoveDeleteCommand.java
  src/main/java/seedu/command/SelectCommand.java
  src/main/java/seedu/command/UnknownCommand.java
  src/main/java/seedu/command/ViewCommand.java
  src/main/java/seedu/exceptions/EmptyListException.java
  src/main/java/seedu/exceptions/IngredientPriceFormatException.java
  src/main/java/seedu/exceptions/InvalidIngredientFormatException.java
  src/main/java/seedu/exceptions/InvalidMcostException.java
  src/main/java/seedu/exceptions/InvalidPriceException.java
  src/main/java/seedu/exceptions/RemoveFormatException.java
  src/main/java/seedu/ezmealplan/EZMealPlan.java
  src/main/java/seedu/food/Ingredient.java
  src/main/java/seedu/food/Product.java
  src/main/java/seedu/logic/MealManager.java
  src/main/java/seedu/meallist/MealList.java
  src/main/java/seedu/storage/Storage.java
  src/test/java/seedu/command/CreateCommandTest.java
  src/test/java/seedu/command/FilterCommandTest.java
  src/test/java/seedu/command/SelectCommandTest.java
  src/test/java/seedu/command/ViewCommandTest.java
  src/test/java/seedu/ezmealplan/EZMealPlanTest.java
  src/test/java/seedu/food/IngredientTest.java
  src/test/java/seedu/food/MealTest.java
  src/test/java/seedu/meallist/MealListTest.java
  src/test/java/seedu/ui/UserInterfaceTest.java
  text-ui-test/input.txt
Labels: type.Bug, priority.High

#178 Branch fix mistakes continuous
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/BootingUpEZMealPlan.png
  docs/diagrams/ConstructingMainMeals.png
  docs/diagrams/ConstructingRecipesList.png
  docs/diagrams/CreateChecker.png
  docs/diagrams/CreateCommand.png
  src/main/java/seedu/checkers/BuyChecker.java
  src/main/java/seedu/checkers/CreateChecker.java
  src/main/java/seedu/checkers/FilterSelectChecker.java
  src/main/java/seedu/checkers/SelectChecker.java
  src/main/java/seedu/checkers/ViewChecker.java
  src/main/java/seedu/command/CreateCommand.java
  src/main/java/seedu/command/DeleteCommand.java
  src/main/java/seedu/command/FilterSelectCommand.java
  src/main/java/seedu/command/HelpCommand.java
  src/main/java/seedu/command/SelectCommand.java
  src/main/java/seedu/command/ViewCommand.java
  src/main/java/seedu/exceptions/InvalidIngredientFormatException.java
  src/main/java/seedu/exceptions/InvalidPriceException.java
  src/main/java/seedu/ezmealplan/EZMealPlan.java
  src/main/java/seedu/food/Ingredient.java
  src/main/java/seedu/logic/MealManager.java
  src/main/java/seedu/parser/Parser.java
  src/test/java/seedu/checkers/CreateCheckerTest.java
  src/test/java/seedu/command/ByeCommandTest.java
  src/test/java/seedu/command/CreateCommandTest.java
  src/test/java/seedu/food/IngredientTest.java
Labels: type.Bug, priority.High

#179 Fix bug with parser
  src/main/java/seedu/command/MistypedCommand.java
  src/main/java/seedu/parser/Parser.java
  src/main/java/seedu/ui/UserInterface.java
  src/test/java/seedu/parser/ParserTest.java
Labels: type.Bug, priority.High

#180 Branch fix mistakes 2
  docs/UserGuide.md
  src/main/java/seedu/command/BuyCommand.java
  src/main/java/seedu/command/CreateCommand.java
  src/main/java/seedu/command/FilterSelectCommand.java
  src/main/java/seedu/exceptions/InvalidMcostException.java
  src/main/java/seedu/exceptions/InvalidPriceException.java
  src/main/java/seedu/ezmealplan/EZMealPlan.java
  src/main/java/seedu/food/Ingredient.java
  src/main/java/seedu/food/Inventory.java
  src/main/java/seedu/food/Meal.java
  src/main/java/seedu/food/Product.java
  src/main/java/seedu/meallist/MealList.java
  src/main/java/seedu/storage/Storage.java
  src/test/java/seedu/command/ViewCommandTest.java
  src/test/java/seedu/food/MealTest.java
Labels: type.Bug, priority.High

#182 Correct the HelpCommand syntex
  src/main/java/seedu/exceptions/MissingIngKeywordException.java
Labels: priority.High

#183 Update Developer Guide
  docs/DeveloperGuide.md
  docs/diagrams/CreateChecker.png
  docs/diagrams/CreateCommand.png
  docs/diagrams/FilterChecker.png
  docs/diagrams/FilterCommand.png
  docs/diagrams/SelectChecker.png
  src/main/java/seedu/checkers/SelectChecker.java
Labels: type.Story, priority.High

#191 Update parser
  src/main/java/seedu/exceptions/ParserException.java
  src/main/java/seedu/ezmealplan/EZMealPlan.java
  src/main/java/seedu/parser/Parser.java
  src/test/java/seedu/parser/ParserTest.java
  text-ui-test/EXPECTED.TXT
Labels: priority.Medium

#186 Add RemoveCommand and RemoveDeleteChecker sequence diagrams
  docs/DeveloperGuide.md
  docs/diagrams/ClearCommand.png
  docs/diagrams/HelpCommand.png
  docs/diagrams/RemoveCommand.png
  docs/diagrams/RemoveDeleteChecker.png
  docs/diagrams/ViewChecker.png
  docs/diagrams/ViewCommand.png
  src/main/java/seedu/command/MistypedCommand.java
  src/main/java/seedu/parser/Parser.java
Labels: type.Story, priority.High

#197 Add ability to remove from Inventory by Ingredient
  src/main/java/seedu/checkers/ConsumeChecker.java
  src/main/java/seedu/command/ConsumeCommand.java
  src/main/java/seedu/food/Inventory.java
  src/test/java/seedu/command/ConsumeCommandTest.java
Labels: priority.High

#198 Add BuyChecker and BuyCommand sequence diagrams
  docs/DeveloperGuide.md
  docs/diagrams/BuyChecker.png
  docs/diagrams/BuyCommand.png
Labels: type.Story, priority.High

#199 Add and update tests for RemoveCommand and DeleteCommand
  src/main/java/seedu/food/Ingredient.java
  src/main/java/seedu/ui/UserInterface.java
  src/test/java/seedu/command/DeleteCommandTest.java
  src/test/java/seedu/command/InventoryCommandTest.java
  src/test/java/seedu/command/MistypedCommandTest.java
  src/test/java/seedu/command/RecipesCommandTest.java
  src/test/java/seedu/command/RemoveCommandTest.java
  src/test/java/seedu/command/UnknownCommandTest.java
  src/test/java/seedu/ui/UserInterfaceTest.java
Labels: priority.High

#202 Improve Test Coverage
  src/main/java/seedu/exceptions/EZMealPlanException.java
  src/main/java/seedu/exceptions/InvalidViewIndexException.java
  src/main/java/seedu/exceptions/InvalidViewKeywordException.java
  src/main/java/seedu/food/Ingredient.java
  src/main/java/seedu/food/Inventory.java
  src/main/java/seedu/food/Meal.java
  src/main/java/seedu/meallist/MealList.java
  src/test/java/seedu/checkers/ViewCheckerTest.java
  src/test/java/seedu/command/BuyCommandTest.java
  src/test/java/seedu/command/ConsumeCommandTest.java
  src/test/java/seedu/command/CreateCommandTest.java
  src/test/java/seedu/command/InventoryCommandTest.java
  src/test/java/seedu/command/ViewCommandTest.java
  src/test/java/seedu/food/InventoryTest.java
  src/test/java/seedu/meallist/MealListTest.java
Labels: priority.High, priority.Medium

#194 Update UML and correct typos in UG
  docs/UserGuide.md
  docs/diagrams/RecipesCommand.png
  docs/diagrams/SelectCommand.png
  docs/diagrams/WishlistCommand.png
  docs/team/olsonwangyj.md
Labels: priority.High
