Repository AY2425S2-CS2113-F14-4/tp, pull requests merged in 2025-03, with the labels that each got.

#13 Add some basic Junit tests for Meal and Ingredient Class
  src/main/java/seedu/exceptions/DuplicateIngredientException.java
  src/main/java/seedu/exceptions/EZMealPlanException.java
  src/main/java/seedu/exceptions/IngredientPriceFormatException.java
  src/main/java/seedu/exceptions/InvalidPriceException.java
  src/main/java/seedu/food/Ingredient.java
  src/main/java/seedu/food/Meal.java
  src/main/java/seedu/food/Product.java
  src/test/java/seedu/food/MealTest.java
Labels: type.Task, priority.High

#31 Branch filter select
  src/main/java/seedu/checkers/Checker.java
  src/main/java/seedu/checkers/CreateChecker.java
  src/main/java/seedu/checkers/FilterChecker.java
  src/main/java/seedu/checkers/FilterSelectChecker.java
  src/main/java/seedu/checkers/SelectChecker.java
  src/main/java/seedu/command/Command.java
  src/main/java/seedu/command/CreateCommand.java
  src/main/java/seedu/command/FilterCommand.java
  src/main/java/seedu/command/FilterSelectCommand.java
  src/main/java/seedu/command/ListCommand.java
  src/main/java/seedu/command/MealCommand.java
  src/main/java/seedu/command/SelectCommand.java
  src/main/java/seedu/exceptions/DuplicateIngredientException.java
  src/main/java/seedu/exceptions/DuplicateMealException.java
  src/main/java/seedu/exceptions/IngredientPriceFormatException.java
  src/main/java/seedu/exceptions/InvalidFilterMethodException.java
  src/main/java/seedu/exceptions/InvalidIngIndexException.java
  src/main/java/seedu/exceptions/InvalidMcostException.java
  src/main/java/seedu/exceptions/InvalidMcostIndexException.java
  src/main/java/seedu/exceptions/InvalidMnameIndexException.java
  src/main/java/seedu/exceptions/InvalidPriceException.java
  src/main/java/seedu/exceptions/InvalidSelectIndexException.java
  src/main/java/seedu/exceptions/MissingIngredientException.java
  src/main/java/seedu/exceptions/MissingMealCostException.java
  src/main/java/seedu/exceptions/MissingMealIndexException.java
  src/main/java/seedu/exceptions/MissingMealNameException.java
  src/main/java/seedu/ezmealplan/EZMealPlan.java
  src/main/java/seedu/food/Meal.java
  src/main/java/seedu/logic/MealManager.java
  src/main/java/seedu/meallist/MainList.java
  src/main/java/seedu/meallist/MealList.java
  src/main/java/seedu/meallist/UserList.java
  src/main/java/seedu/parser/Parser.java
  src/main/java/seedu/storage/Storage.java
  src/main/java/seedu/ui/UserInterface.java
  src/test/java/seedu/checkers/CreateCheckerTest.java
  text-ui-test/EXPECTED.TXT
Labels: type.Task, priority.High

#36 Branch bug fix
  data/mainList.txt
  src/main/java/seedu/ezmealplan/EZMealPlan.java
  src/main/java/seedu/storage/Storage.java
Labels: type.Bug, severity.Medium

#39 Branch view
  src/main/java/seedu/checkers/ViewChecker.java
  src/main/java/seedu/command/ViewCommand.java
  src/main/java/seedu/exceptions/InvalidFilterMethodException.java
  src/main/java/seedu/exceptions/InvalidKeywordIndexException.java
  src/main/java/seedu/exceptions/InvalidMcostException.java
  src/main/java/seedu/exceptions/InvalidSelectIndexException.java
  src/main/java/seedu/exceptions/InvalidViewIndexException.java
  src/main/java/seedu/exceptions/InvalidViewKeywordException.java
  src/main/java/seedu/exceptions/RemoveFormatException.java
  src/main/java/seedu/exceptions/ViewIndexOutOfRangeException.java
  src/main/java/seedu/parser/Parser.java
  src/main/java/seedu/ui/UserInterface.java
Labels: type.Task, priority.High

#53 Branch junit create
  src/main/java/seedu/command/CreateCommand.java
  src/main/java/seedu/exceptions/DuplicateIngredientException.java
  src/main/java/seedu/exceptions/DuplicateMealException.java
  src/main/java/seedu/food/Meal.java
  src/test/java/seedu/checkers/CreateCheckerTest.java
  src/test/java/seedu/checkers/RemoveDeleteCheckerTest.java
  src/test/java/seedu/command/CreateCommandTest.java
  src/test/java/seedu/command/ListCommandTest.java
  src/test/java/seedu/command/MealCommandTest.java
  text-ui-test/EXPECTED.TXT
Labels: type.Task, priority.High

#58 Branch JUnit Test Food
  src/main/java/seedu/command/CreateCommand.java
  src/main/java/seedu/food/Ingredient.java
  src/main/java/seedu/food/Meal.java
  src/main/java/seedu/food/Product.java
  src/main/java/seedu/storage/Storage.java
  src/test/java/seedu/food/IngredientTest.java
  src/test/java/seedu/food/MealTest.java
  src/test/java/seedu/ui/UserInterfaceTest.java
Labels: type.Task, priority.High

#56 Update DG for ListCommand and MealCommand
  .gitignore
  docs/DeveloperGuide.md
  docs/ListCommand.png
  docs/MealCommand.png
  src/main/java/seedu/command/ListCommand.java
  src/main/java/seedu/command/MealCommand.java
  src/test/java/seedu/ui/ListCommandTest.java
Labels: priority.High

#66 Did Junit Tests for FilterCommand, SelectCommand, FilterChecker, SelectChecker and other miscellaneous updates
  src/main/java/seedu/checkers/SelectChecker.java
  src/main/java/seedu/command/FilterSelectCommand.java
  src/main/java/seedu/exceptions/DuplicateMealException.java
  src/main/java/seedu/exceptions/InvalidMcostException.java
  src/main/java/seedu/exceptions/InvalidPriceException.java
  src/main/java/seedu/ezmealplan/EZMealPlan.java
  src/main/java/seedu/meallist/Meals.java
  src/main/java/seedu/parser/Parser.java
  src/test/java/seedu/checkers/CreateCheckerTest.java
  src/test/java/seedu/checkers/FilterCheckerTest.java
  src/test/java/seedu/checkers/RemoveDeleteCheckerTest.java
  src/test/java/seedu/checkers/SelectCheckerTest.java
  src/test/java/seedu/command/CreateCommandTest.java
  src/test/java/seedu/command/FilterCommandTest.java
  src/test/java/seedu/command/ListCommandTest.java
  src/test/java/seedu/command/MealCommandTest.java
  src/test/java/seedu/command/SelectCommandTest.java
  src/test/java/seedu/food/IngredientTest.java
  src/test/java/seedu/ui/ListCommandTest.java
  src/test/java/seedu/ui/MealCommandTest.java
  src/test/java/seedu/ui/UserInterfaceTest.java
Labels: type.Task, priority.High
